# 1. Базовый образ
FROM node:18

# 2. Рабочая директория внутри контейнера
WORKDIR /app

# 3. Копируем package.json
COPY package*.json ./

# 4. Устанавливаем зависимости
RUN npm install

# 5. Копируем весь проект
COPY . .

# 6. Указываем порт
EXPOSE 3000

# 7. Команда запуска
CMD ["npm", "run", "dev"]